# Allow flags to travel to the End. Allowing this risks loss of flags to the Void.
allowEnd: false

# Behavior when a player quits with a flag in their inventory.
# DROP: Drops the flag from the player's inventory.
# KILL: Kills the player.
quitMode: "DROP"

# By default, the plugin will launch firework particles every minute from the flag to help players
# find it. It is recommended to keep this enabled if using item flags, as the client will not track
# items from more than ~20 blocks away.
useParticleBeacon: true