name: CTFBuddy
version: '${version}'
main: io.github.minus1over12.ctfbuddy.CTFBuddy
api-version: '1.20'
author: War Pigeon
description: Automated system for CTF
commands:
  makeflag:
    description: Creates a new flag.
    usage: |-
      /<command> item
      /<command> entity [<uuid>]
    permission: CTFBuddy.makeflag
permissions:
  mcjctf.makeflag:
    description: Allows the player to create a flag using /makeflag.
    default: op